name: Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  print-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print success
        run: echo "Hello, the testing of pipeline has been success!"
